FROM python:3.9-slim

WORKDIR /app
COPY app.py .
RUN pip install flask requests opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp-proto-http opentelemetry-instrumentation-flask opentelemetry-instrumentation-requests opentelemetry-exporter-prometheus

EXPOSE 5000
CMD ["python", "app.py"]