apiVersion: v1
kind: Service
metadata:
  name: content-creator-service
  namespace: default
  labels:
    app: content-creator
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
  selector:
    app: content-creator
