#deploymentMode: SingleBinary
loki:
  deploymentMode: SingleBinary
#  config:
#    mode: SingleBinary
  storage:
    type: filesystem
persistence:
  enabled: true
  storageClass: standard
  size: 10Gi