service:
  type: NodePort
  port: 80
  nodePort: 30000
adminUser: admin
adminPassword: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      access: proxy
      isDefault: true
      uid: prometheus
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
    - name: Jaeger
      type: jaeger
      url: http://jaeger.monitoring.svc.cluster.local:16686
      access: proxy