apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686  # Web UI
        - containerPort: 4317   # OTel gRPC
        - containerPort: 4318   # OTel HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
  - name: web
    port: 16686
    targetPort: 16686
  - name: otel-grpc
    port: 4317
    targetPort: 4317
  - name: otel-http
    port: 4318
    targetPort: 4318