apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Use the official ArgoCD install manifest (simplified for Minikube)
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: argocd-server
    #app.kubernetes.io/name: NodePort
  type: NodePort
---
# Full manifest truncated for brevity; download from official source
# Source: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml