apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: default
  labels:
    app: content-service
spec:
  type: NodePort
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
  selector:
    app: content-service
